version: "3.1"
services:
  config:
    build:
      context: ./ #dockerfile所在文件夹路径
      dockerfile: Dockerfile #dockerfile的名称
    container_name: config
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai   #docker时区调整

